package com.wordpress.utils.conn;

import com.wordpress.utils.log.Log;
/*
 * DO NOT EDIT THIS FILE
 * This is a dummy file.  The file with the private BIS key overwrites this one during build
 */
public class BISConfig extends AbstractConfiguration {
	
    protected static final String CONFIG_DESCRIPTION = "BIS Configuration";
	    
	public BISConfig() {
		super();
        Log.debug("Setting BIS Config " + " " + CONFIG_DESCRIPTION);
        setUrlParameters(";deviceside=false");
        setDescription(CONFIG_DESCRIPTION);
	}
}
